#!/bin/bash

# ============================================
# TACACS+ Server Setup Script for Ubuntu
# ============================================
# This script installs and configures TACACS+
# server on Ubuntu with all necessary settings
# ============================================

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration Variables (MODIFY THESE AS NEEDED)
TACACS_KEY="your-tacacs-shared-secret-key-here"
TACACS_USER="admin"
TACACS_PASSWORD="changeme123"
TACACS_CONFIG_DIR="/etc/tacacs+"
TACACS_CONFIG_FILE="${TACACS_CONFIG_DIR}/tac_plus.conf"
TACACS_LOG_FILE="/var/log/tac_plus.log"

# Function to print colored output
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    print_error "Please run as root (use sudo)"
    exit 1
fi

print_info "Starting TACACS+ Server Setup..."

# Update package list
print_info "Updating package list..."
apt-get update -qq

# Install TACACS+ server
# To avoid overcomplicating things on this EOL Ubuntu release,
# we no longer try to install TACACS+ automatically here.
# We assume the tac_plus binary is already present (which it is on your VM now),
# and only manage configuration and the systemd service.
print_info "Checking for existing TACACS+ binary..."
if ! command -v tac_plus >/dev/null 2>&1 && [ ! -x "/usr/sbin/tac_plus" ]; then
    print_error "tac_plus binary not found on this system."
    echo "Please install TACACS+ once manually on this VM, then re-run this script."
    echo ""
    echo "Example manual install:"
    echo "  apt-get update"
    echo "  apt-get install -y build-essential wget default-libmysqlclient-dev"
    echo "  cd /tmp"
    echo "  wget -O tac_plus-4.6b3-5.tgz https://downloads.sourceforge.net/project/tac-plus/tac_plus-4.6b3-5.tgz"
    echo "  mkdir tac_plus-src && tar -xzf tac_plus-4.6b3-5.tgz -C tac_plus-src"
    echo "  cd tac_plus-src && make && install tac_plus /usr/sbin"
    exit 1
fi
print_info "TACACS+ binary found; proceeding with configuration."

# Create configuration directory if it doesn't exist
print_info "Creating configuration directory..."
mkdir -p "${TACACS_CONFIG_DIR}"

# Backup existing config if it exists
if [ -f "${TACACS_CONFIG_FILE}" ]; then
    print_warn "Backing up existing configuration..."
    cp "${TACACS_CONFIG_FILE}" "${TACACS_CONFIG_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Create TACACS+ configuration file
print_info "Creating TACACS+ configuration file..."
cat > "${TACACS_CONFIG_FILE}" << EOF
# ============================================
# TACACS+ Server Configuration
# Generated by setup_tacacs.sh
# ============================================

# Key for TACACS+ communication
key = "${TACACS_KEY}"

# Accounting file
accounting file = ${TACACS_LOG_FILE}

# Default authentication method
default authentication = file

# User definitions
user = ${TACACS_USER} {
    # Password encrypted with tac_pwd (use 'tac_pwd' command to generate)
    # Default password: ${TACACS_PASSWORD}
    # To change password, run: tac_pwd
    login = cleartext ${TACACS_PASSWORD}
    
    # Service definitions
    service = ppp {
        protocol = ip
    }
    service = shell {
        priv-lvl = 15
        cmd = permitall
    }
}

# Group definitions (optional)
group = admins {
    default service = permit
    service = shell {
        priv-lvl = 15
        cmd = permitall
    }
}

# Group for network devices
group = network {
    default service = permit
    service = shell {
        priv-lvl = 15
        cmd = permitall
    }
}

# Default group
group = default {
    default service = permit
    service = shell {
        priv-lvl = 1
        cmd = permitall
    }
}

# Host definitions (optional - for device-specific access)
# host = router1 {
#     address = 192.168.1.1
#     key = "device-specific-key"
# }
EOF

print_info "Configuration file created at ${TACACS_CONFIG_FILE}"

# Ensure tacacs group exists, then set proper permissions
if ! getent group tacacs >/dev/null 2>&1; then
    print_info "Creating 'tacacs' group for TACACS+ configuration ownership..."
    groupadd --system tacacs || print_warn "Could not create 'tacacs' group; using root:root for config file ownership."
fi

chmod 640 "${TACACS_CONFIG_FILE}"
if getent group tacacs >/dev/null 2>&1; then
    chown root:tacacs "${TACACS_CONFIG_FILE}"
else
    chown root:root "${TACACS_CONFIG_FILE}"
fi

# Create log file and set permissions
print_info "Setting up log file..."
touch "${TACACS_LOG_FILE}"
chmod 644 "${TACACS_LOG_FILE}"
chown root:root "${TACACS_LOG_FILE}"

# Create systemd service file (if not exists)
print_info "Configuring systemd service..."
SERVICE_FILE="/etc/systemd/system/tacacs.service"

if [ ! -f "${SERVICE_FILE}" ]; then
    cat > "${SERVICE_FILE}" << EOF
[Unit]
Description=TACACS+ Authentication Server
After=network.target

[Service]
Type=forking
ExecStart=/usr/sbin/tac_plus -C ${TACACS_CONFIG_FILE}
ExecReload=/bin/kill -HUP \$MAINPID
PIDFile=/var/run/tac_plus.pid
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    print_info "Systemd service file created"
else
    print_info "Systemd service file already exists"
fi

# Enable and start TACACS+ service
print_info "Enabling TACACS+ service..."
systemctl enable tacacs.service

print_info "Starting TACACS+ service..."
if systemctl start tacacs.service; then
    print_info "TACACS+ service started successfully"
else
    print_error "Failed to start TACACS+ service"
    print_info "Checking service status..."
    systemctl status tacacs.service
    exit 1
fi

# Check if service is running
sleep 2
if systemctl is-active --quiet tacacs.service; then
    print_info "TACACS+ service is running"
else
    print_error "TACACS+ service is not running"
    systemctl status tacacs.service
    exit 1
fi

# Configure firewall (UFW)
print_info "Configuring firewall..."
if command -v ufw &> /dev/null; then
    if ufw status | grep -q "Status: active"; then
        print_info "UFW is active, adding TACACS+ port (49)"
        ufw allow 49/tcp comment "TACACS+"
        print_info "Firewall rule added"
    else
        print_warn "UFW is not active, skipping firewall configuration"
    fi
else
    print_warn "UFW not installed, skipping firewall configuration"
fi

# Display configuration summary
echo ""
print_info "============================================"
print_info "TACACS+ Server Setup Complete!"
print_info "============================================"
echo ""
print_info "Configuration Details:"
echo "  Config File: ${TACACS_CONFIG_FILE}"
echo "  Log File: ${TACACS_LOG_FILE}"
echo "  Shared Key: ${TACACS_KEY}"
echo "  Default User: ${TACACS_USER}"
echo "  Default Password: ${TACACS_PASSWORD}"
echo ""
print_warn "IMPORTANT SECURITY NOTES:"
echo "  1. Change the default password immediately!"
echo "  2. Update the shared key (TACACS_KEY) in this script"
echo "  3. Review and customize ${TACACS_CONFIG_FILE}"
echo "  4. Configure firewall rules as needed"
echo ""
print_info "Useful Commands:"
echo "  Check status: systemctl status tacacs"
echo "  View logs: tail -f ${TACACS_LOG_FILE}"
echo "  Restart service: systemctl restart tacacs"
echo "  Test configuration: tac_plus -C ${TACACS_CONFIG_FILE} -d 4"
echo ""
print_info "To add more users, edit ${TACACS_CONFIG_FILE}"
print_info "and restart the service: systemctl restart tacacs"
echo ""

